[project]
drom-version = "0.1"

[project]
authors = ["Ben Simms <ben@bensimms.moe>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "Ben Simms <ben@bensimms.moe>"
edition = "4.10.0"
license = "MIT"
min-edition = "4.07.0"
name = "advent-of-code-2021"
synopsis = "The advent-of-code-2021 project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."
# github-organization = "...github-organization..."

[project]
description = """My solutions to the AOC 2021
"""

[project]
skip = []

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools]
camelot = ""
ocaml-lsp-server = ""
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/advent-of-code-2021"
# edit 'src/advent-of-code-2021/package.toml' for package-specific options

[[package]]
dir = "src/day1"
# edit 'src/day1/package.toml' for package-specific options

